class Solution {
    public:
        int compress(vector<char>& chars) {
                string s="";
                        if(chars.size()==1){
                                    return 1;
                                            }
                                                    // sort(chars.begin(),chars.end());
                                                            int m=1;
                                                                    if(chars.size())
                                                                            for(int i=0;i<chars.size()-1;i++){
                                                                                        if(chars.size()>2&&i==chars.size()-2&&chars[i]==chars[i-1]&&chars[i]!=chars[i+1]){
                                                                                                        s=s+chars[i];
                                                                                                                        s=s+to_string(m);
                                                                                                                                        s=s+chars[i+1];
                                                                                                                                                    }
                                                                                                                                                                else if(chars[i]!=chars[i+1]||i==chars.size()-2){
                                                                                                                                                                                if(m==1){
                                                                                                                                                                                                    if(chars[i]==chars[i+1]){
                                                                                                                                                                                                                            s=s+chars[i];
                                                                                                                                                                                                                                                    s=s+"2";
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                            else{
                                                                                                                                                                                                                                                                                                                    if(i==chars.size()-2){
                                                                                                                                                                                                                                                                                                                                                s=s+chars[i]+chars[i+1];
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                else s=s+chars[i];
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    else{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        s=s+chars[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(i==chars.size()-2){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    s=s+to_string(m+1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else s=s+to_string(m);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            m=1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    m++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout<<s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for(int i=0;i<s.size();i++){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    chars[i]=(s[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return s.size();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };